// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-portfolio.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_portfolio_default = defineTool({
  name: "list_portfolio",
  title: "List portfolio projects",
  description: "List portfolio projects. Non-admins only see published projects; admins see all.",
  inputSchema: {
    status: z.enum(["published", "draft", "any"]).optional().describe("Filter by status. Defaults to published."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("portfolio").select("id, title, category, short_description, project_url, image_url, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status && status !== "any") query = query.eq("status", status);
    else if (!status) query = query.eq("status", "published");
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-portfolio.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_portfolio_default = defineTool2({
  name: "get_portfolio",
  title: "Get portfolio project",
  description: "Fetch a single portfolio project by id, including gallery and videos.",
  inputSchema: { id: z2.string().uuid().describe("Portfolio project id (UUID).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser2(ctx).from("portfolio").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/create-portfolio.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_portfolio_default = defineTool3({
  name: "create_portfolio",
  title: "Create portfolio project",
  description: "Create a portfolio project. Requires an admin account (enforced by row-level security).",
  inputSchema: {
    title: z3.string().min(1),
    category: z3.string().optional(),
    short_description: z3.string().optional(),
    long_description: z3.string().optional(),
    project_url: z3.string().url().optional(),
    image_url: z3.string().url().optional(),
    tags: z3.array(z3.string()).optional(),
    gallery: z3.array(z3.string().url()).optional(),
    videos: z3.array(z3.string().url()).optional(),
    status: z3.enum(["draft", "published"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).from("portfolio").insert(input).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created portfolio ${data.id}` }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/update-portfolio.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_portfolio_default = defineTool4({
  name: "update_portfolio",
  title: "Update portfolio project",
  description: "Update fields on a portfolio project. Requires admin (enforced by RLS).",
  inputSchema: {
    id: z4.string().uuid(),
    title: z4.string().optional(),
    category: z4.string().optional(),
    short_description: z4.string().optional(),
    long_description: z4.string().optional(),
    project_url: z4.string().url().optional(),
    image_url: z4.string().url().optional(),
    tags: z4.array(z4.string()).optional(),
    gallery: z4.array(z4.string().url()).optional(),
    videos: z4.array(z4.string().url()).optional(),
    status: z4.enum(["draft", "published"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser4(ctx).from("portfolio").update(patch).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Updated portfolio ${id}` }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool5({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List blog posts. Non-admins only see published posts; admins can filter by status.",
  inputSchema: {
    status: z5.enum(["published", "draft", "any"]).optional(),
    limit: z5.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser5(ctx).from("blog_posts").select("id, title, slug, category, excerpt, status, published_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status && status !== "any") q = q.eq("status", status);
    else if (!status) q = q.eq("status", "published");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_blog_post_default = defineTool6({
  name: "create_blog_post",
  title: "Create blog post",
  description: "Create a blog post. Requires admin (enforced by RLS).",
  inputSchema: {
    title: z6.string().min(1),
    slug: z6.string().min(1).describe("URL slug. Must be unique."),
    excerpt: z6.string().optional(),
    content: z6.string().optional(),
    category: z6.string().optional(),
    cover_image_url: z6.string().url().optional(),
    tags: z6.array(z6.string()).optional(),
    gallery: z6.array(z6.string().url()).optional(),
    reading_time: z6.number().int().positive().optional(),
    status: z6.enum(["draft", "published"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const payload = { ...input };
    if (input.status === "published") payload.published_at = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await supabaseForUser6(ctx).from("blog_posts").insert(payload).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created blog post ${data.id}` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-testimonials.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^4.4.3";
function supabaseForUser7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_testimonials_default = defineTool7({
  name: "list_testimonials",
  title: "List client testimonials",
  description: "List client testimonials. Non-admins only see published ones.",
  inputSchema: {
    status: z7.enum(["published", "draft", "any"]).optional(),
    limit: z7.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser7(ctx).from("testimonials").select("*").order("display_order", { ascending: true }).limit(limit ?? 50);
    if (status && status !== "any") q = q.eq("status", status);
    else if (!status) q = q.eq("status", "published");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { testimonials: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-contact-messages.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z8 } from "npm:zod@^4.4.3";
function supabaseForUser8(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contact_messages_default = defineTool8({
  name: "list_contact_messages",
  title: "List contact form messages",
  description: "List messages submitted through the public contact form. Admin-only (enforced by RLS).",
  inputSchema: {
    unread_only: z8.boolean().optional().describe("If true, return only unread messages."),
    limit: z8.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser8(ctx).from("contact_messages").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (unread_only) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/mark-message-read.ts
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z9 } from "npm:zod@^4.4.3";
function supabaseForUser9(ctx) {
  return createClient9(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var mark_message_read_default = defineTool9({
  name: "mark_message_read",
  title: "Mark contact message as read",
  description: "Mark a contact form message as read (or unread). Admin-only.",
  inputSchema: {
    id: z9.string().uuid(),
    is_read: z9.boolean().optional().describe("Defaults to true.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, is_read }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser9(ctx).from("contact_messages").update({ is_read: is_read ?? true }).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Message ${id} updated.` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mkirvbgiirmxigrtwzqz";
var mcp_default = defineMcp({
  name: "rufus-akande-mcp",
  title: "Rufus Akande Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools to read and manage the Rufus Akande portfolio, blog posts, client testimonials, and contact messages. Non-admin accounts can only read published content; admins can create/update content and view contact messages.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_portfolio_default,
    get_portfolio_default,
    create_portfolio_default,
    update_portfolio_default,
    list_blog_posts_default,
    create_blog_post_default,
    list_testimonials_default,
    list_contact_messages_default,
    mark_message_read_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
